### ISSUE TITLE
Using { logout } in useAuthActions() action does not affect {authenticated} state in other tabs

### ISSUE THREAD

**Issue by nicokunz** [inmagik/use-eazy-auth#25]
Thanks for making a nifty library.

One of the issues we have come across is that using the logout action does not affect other tabs with the app open. How do we get the log out action to update the authenticated state in useAuthState when logout is actioned. API requests continue to work in the other tabs because the components have not re-rendered and they 'remember' the JWT token even if it has been cleared from localStorage.

The current work around is to check state at very short intervals but this is not ideal.

Ideally logging out should cause the `const { authenticated } = useAuthState();` to update and re-render across tabs.

**Comment by gffuma** [comment]
Hey @nicokunz thanks for appreciation.

It's not straightforward but you can implement it by yourself on top of eazy auth.
It's the sample code:
This implementation is based on [BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel) to comunicate between tabs you can also polyfill them.

```jsx
function LogOutFromTabs() {
  const { logout } = useAuthActions()
  useEffect(() => {
    const channel = new window.BroadcastChannel('auth')
    function handleMessage(msg) {
      if (msg.data.type === 'logout') {
        logout()
      }
    }
    channel.addEventListener('message', handleMessage)
    return () => channel.removeEventListener('message', handleMessage)
  })
  return null
}

const App = () => (
  <Auth
    loginCall={loginCall}
    meCall={meCall}
    refreshTokenCall={refreshTokenCall}
    onLogout={() => {
      const channel = new window.BroadcastChannel('auth')
      channel.postMessage({ type: 'logout' })
    }}
  >
    <>
      <LogOutFromTabs />
      {/* ... Rest of your app ... */}
    </>
  </Auth>
)
```

Let me know if this solution works for you 🎸 🎸 🎸

**Comment by nicokunz** [comment]
@gffuma this worked great. Thank you so much for your help!
